### ISSUE TITLE
Version of fork

### ISSUE THREAD

**Issue by progtw** [tdhock/inlinedocs#1]
What r-forge svn revision of inlinedocs was forked to github?
When I compare the recent version on r-forge, there are differences to the oldest version on github
(Version, missing Maintainer field, ...)

**Comment by tdhock** [comment]
markus' re-design on R-Forge was not working for me, so I think I took the most recent version before his changes, 

https://r-forge.r-project.org/scm/viewvc.php?view=rev&root=inlinedocs&revision=393
