### ISSUE TITLE
Maintainer field in DESCRIPTION

### ISSUE THREAD

**Issue by progtw** [tdhock/inlinedocs#2]
With R version 3.1.2 I get errors from R CHECK that the maintainer field is missing. Adding the field in addition to Authors@R should not harm newer R versions but support backward compatibility. I suggest adding the Author and Maintainer fields.

**Comment by tdhock** [comment]
I don't see any errors on R CMD check on travis https://travis-ci.org/tdhock/inlinedocs/builds/65565170

but I added the Maintainer anyway.
